[package]
name = "wasm-rpc"
description = "WASM rpc is a standard interface to programs that compile to WebAssembly"
license = "MIT"
version = "0.2.13"
authors = ["Mason Fischer <mason@kissr.co>"]

[dependencies]
serde_cbor = "0.9.0"
wee_alloc = "0.4.2"
