[package]
name = "error_handler"
version = "0.1.0"
authors = ["Mason Fischer <mason@kissr.co>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-rpc = {path = "../../wasm-rpc"}
wasm-rpc-macros = {path = "../../wasm-rpc-macros"}
